### ISSUE TITLE
`nof_clauses` on a solver does not update after `add_clause`

### ISSUE THREAD

**Issue by garandria** [pysathq/pysat#40] opened 2020-01-23 16:26 UTC
Issue in the title.
Here is an example of code (with comments):

```python
from pysat.formula import CNF
from pysat.solvers import Solver, Glucose3

formula = CNF()
formula.append([-1, 2])

l = Solver(bootstrap_with=formula.clauses)
assert(l.nof_clauses() == 1) # OK
l.add_clause([1, 2])
assert(l.nof_clauses() == 2) # normal

l.add_clause([2])
### should fail
assert(l.nof_clauses() == 2) # 3 expected


################# second example

formula2 = CNF()
formula2.append([-1, 2])

l2 = Solver(bootstrap_with=formula2.clauses)
assert(l2.nof_clauses() == 1) # OK

l2.add_clause([2])
### should fail
assert(l2.nof_clauses() == 1) # 2 expected
```
Thanks for your help

**Comment by alexeyignatiev** [comment] 2020-01-23 21:06
Hi @garandria,

Thanks for reporting but this is not a bug. Unlike other clauses, unit size clauses are stored in MiniSat and its descendants in a separate data structure. As a result, unit clauses are not taken into account as normal clauses by the solver itself. Since method `nof_clauses()` asks the solver to give the current number of clauses, it reports the number, with no unit clauses counted.

If you want to count the number of all clauses, you can either (1) work with class `CNF` or `WCNF` or (2) count the number on your own.

Hope this helps,
Alexey

**Comment by garandria** [comment] 2020-01-23 21:50
Thanks for your answer.
How should I do if I want to add progressively some clauses (including unit clause) in the solver in order to check its satisfiability ? Should I add the clause in the cnf first then build a new Solver then solve this last ?
Thanks

**Comment by alexeyignatiev** [comment] 2020-01-23 22:38
It is fine to just add them to the solver the way you do it now. The only (minor) issue would be the one you spotted, i.e. the number of clauses will be reported incorrectly due to unit clauses.

I am going to close this issue. If you want to reopen, feel free to do so.

**Closed by alexeyignatiev** 2020-01-23 22:38 UTC

**Comment by FAMILIAR-project** [comment] 2020-01-24 10:51
Hi @alexeyignatiev, 

thanks for clarifying! 

just to be sure: Is it semantically the same to use `add_clause([1])` (for adding a unit clause) and `solve(assumptions=[1])`?

**Comment by alexeyignatiev** [comment] 2020-01-24 11:49
Hi @FAMILIAR-project,

Yes, you can say these options are semantically the same. The only difference is how this unit clause is handled internally, which may lead to different performance results.

The thing is that the latter option uses an assumption literal, which adds the flexibility of *incremental solving*, i.e. you can later call the same solver with the unit clause discarded. By using incrementality, you may end up paying the price of decreased performance. The former option does not allow you to discard unit clauses specified as assumptions but, in general, it should be more efficient.

Alexey
