### ISSUE TITLE
enum_models messes up the formula (not reusable)

### ISSUE THREAD

**Issue by hellman** [pysathq/pysat#81] opened 2021-05-06 13:48 UTC
It seems `s.enum_models()` messes up the formula which becomes unsolvable afterwards, even after adding new clauses.

Also it is clear that it adds some clauses (does not clean up clauses used for enumeration?).

This does not happen with `s.get_model()`.

Cloned from git ( 17cb05c037b90d8eeb9c72736e5bc6946bd407fe ), also tried with the PyPI version.

```python
from pysat.solvers import Solver
from pysat import __version__
print(__version__)
s = Solver(name='cadical')
s.add_clause([-1, 2])
s.add_clause([-1, -2])
print("solve", s.solve())
print("clauses", s.nof_clauses())
print("models", list(s.enum_models()))
print("clauses", s.nof_clauses())
print("solve", s.solve())
print("models", list(s.enum_models()))
print("clauses", s.nof_clauses())
```

```
0.1.7.dev2
solve True
clauses 2
models [[-1, -2], [-1, 2]]
clauses 4
solve False
models []
clauses 4
```

**Comment by alexeyignatiev** [comment] 2021-05-07 03:50
Yes, this is just a helper method that can be used to enumerate models. And yes, this is how model enumeration normally works, i.e. by adding clauses that block the previous models, until no more models exist. And yes, as a result, the formula ends up being unsatisfiable. This is not a bug.

A more flexible solution can be devised, e.g. using assumption literals to be able to disable all the added clauses after the models are enumerated. You are more than welcome to implement it and use it - it's not a big deal anyway. But I should note that assumptions are likely to result in a slower solution, as usual. That is why it is not used "by default".

**Comment by alexeyignatiev** [comment] 2021-05-24 13:07
A warning is added in the documentation for the method in version 0.1.7.dev3. I am closing the issue.

**Closed by alexeyignatiev** 2021-05-24 13:07 UTC
