### ISSUE TITLE
pep 517 error

### ISSUE THREAD

**Issue by algebravic** [pysathq/pysat#148] opened 2023-10-20 18:09 UTC
I just tried upgrading to 0.1.8.dev10.  I got all sorts of errors regarding noncompliance with PEP517.  Here's a command that provokes the errors:

`pip wheel --use-pep517 "python-sat (==0.1.8.dev10)"`

**Comment by alexeyignatiev** [comment] 2023-10-20 20:33
Well, that's weird as I didn't change anything in the build process! Do you *have to* use this option? What is your system? What version of Python and pip are you using? I will try to understand what this PEP defines, when this occurs and why. (Don't even know what that is!)

**Comment by algebravic** [comment] 2023-10-20 22:05
I was able to install dev9.  I just used the latest version of pip.
However, this might be because there was an error in some of the
compilations.  There’s an absurd amount of errors.  I’ll see if I can
pinpoint it.

**Comment by alexeyignatiev** [comment] 2023-10-21 03:19
Victor, the question is why you use the option `--use-pep517` in the first place. I never even tried to make the build process compatible with this PEP.

**Comment by algebravic** [comment] 2023-10-21 03:55
I manage my dependencies using the poetry package.  It failed to install
dev10, complaining about pep 517.  There was no problem with dev9.  The
error that came up was in the final of command.

**Comment by alexeyignatiev** [comment] 2023-12-14 02:53
I am closing it now as I can't reproduce this.

**Closed by alexeyignatiev** 2023-12-14 02:53 UTC
