### ISSUE TITLE
Error in M1 macOS

### ISSUE THREAD

**Issue by yoni206** [pysathq/pysat#111] opened 2022-08-16 12:48 UTC
I get the following error on an M1 macOS machine (but not on linux), when importing a solver.
Installed via pip.
```
>>> from pysat.solvers import Glucose3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yonizohar/Library/Python/3.8/lib/python/site-packages/pysat/solvers.py", line 157, in <module>
    import pysolvers
ModuleNotFoundError: No module named 'pysolvers'
>>>
```

**Comment by alexeyignatiev** [comment] 2022-08-16 23:35
I don't think we have binary wheels precompiled for M1. I suggest you check what is happening when you are installing the toolkit with pip. There might be a compilation error preventing the `pysolvers` module to be built.

**Comment by yoni206** [comment] 2022-08-17 05:42
Workaround: cloning the repo and running `python3 setup.py install` works.

**Comment by yoni206** [comment] 2022-08-17 10:06
Actually... the workaround does not install `pypblib`... Any idea on how to use `setup.py` to install `pypblib`? Or any other way to install `pypblib`?

**Comment by alexeyignatiev** [comment] 2022-08-17 10:24
You can always try to install it with pip.

**Comment by yoni206** [comment] 2022-08-17 10:27
Thanks. But it seems like there is a problem installing `pysat` and `pypblib` through `pip` on `M1`... Is there a way to build / install from source? Or perhaps even adding some directory from the repo to my `PYTHONPATH`?

**Comment by alexeyignatiev** [comment] 2023-01-11 05:39
Yes, you can surely install `pypblib` from PyPI by compiling it. I have just compiled both toolkits on M1 with no issue. Closing. Feel free to reopen if you believe this to be a general issue.

**Closed by alexeyignatiev** 2023-01-11 05:39 UTC

**Comment by Edisonliiii** [comment] 2024-06-12 11:44
File "<string>", line 1, in <module>
  File "/Users/XXX/miniconda3/envs/daily/lib/python3.10/site-packages/pysat/solvers.py", line 174, in <module>
    import pysolvers
ImportError: dlopen(/Users/XXX/miniconda3/envs/daily/lib/python3.10/site-packages/pysolvers.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN10CaDiCaL1036Solver11trace_proofEP7__sFILEPKc)

I still got this error after normally installing the pysat via pip inside my conda environment.
Any idea?

Here is how i use it


```python
from pysat.formula import CNF
from pysat.solvers import Lingeling

formula = CNF()
formula.append([-1, 2])
formula.append([1, -2])
formula.append([-1, -2])
formula.append([1, 2])
with Lingeling(bootstrap_with=formula.clauses, with_proof=True) as l:
    if l.solve() == False:
        print(l.get_proof())

```

**Comment by alexeyignatiev** [comment] 2024-06-13 00:13
Not sure what to suggest. Apparently, the binary wheel fails to find some of the symbols in your case. You may want to try to compile it on your machine.

**Comment by Edisonliiii** [comment] 2024-06-13 04:15
Background: my platform is 
Darwin XXXX.XXX 21.6.0 Darwin Kernel Version 21.6.0 
[XXXXX]:[XXXXX]/RELEASE_X86_64 x86_64

It might because of the mixture of Clang and GCC, but i am not 100% sure about this. I did successfully install pysat via creating a new conda environment, but I am not so sure why creating a new one works.

I believe there are some space to improve for the installation scripts, and also, I figure that main branch is different from the release. And in the [Version 0.1.7.dev15](https://github.com/pysathq/pysat/releases/tag/0.1.7.dev15), [python-sat-0.1.7.dev15.tar.gz](https://github.com/pysathq/pysat/releases/download/0.1.7.dev15/python-sat-0.1.7.dev15.tar.gz) does not work well for some reason. However, the zip file of the source code works fine.

Directly "git clone" the main branch does not work to me, I keep getting the error which is saying that can not find headers(.hpp) of the solvers. I looked into it, basically, in the main branch, the solvers are all zip files, and for some reason, the "setup.py" can not normally retrieve the headers.

I am not sure how it goes on other platforms, I believe that it works fine on Linux, I did try it. But on MacOS, even if it is not MX series, problems still exist. I am happy to help debug. Also, please correct me if I made any explicit mistakes!

Cheers,
Ed

**Comment by alexeyignatiev** [comment] 2024-06-13 04:17
Hi Ed,

The headers issue you mention suggests you may have a problem with header and library paths on your system in general. It may indeed be caused by multiple compilers you use. Also note that the latest version of the toolkit is "1.8.dev13".

Best,
Alexey

**Comment by Edisonliiii** [comment] 2024-06-13 04:22
Thanks for the promptly reply, I will look into it when I got more time. Also I want to confirm another thing (it not be suitable to mention it in here, but for the sake of convenience. Maybe delete later.), SATLIB benchmark is too trivial for the modern SAT solvers, right? It looks like I can use pysat to solve most of them less than half a second.

If you have no idea, it's totally fine, I will find some other places to ask then.

Thanks!

Cheers,
Ed

**Comment by alexeyignatiev** [comment] 2024-06-13 04:31
Ed, I am not sure about the difficulty of the SATLIB benchmarks to be honest. You should be able to get some challenging ones from the annual SAT Competitions.

**Comment by Edisonliiii** [comment] 2024-06-13 04:32
Alexey, thanks a lot for the replies.
