### ISSUE TITLE
Cardinality constraints using different encodings give different outputs

### ISSUE THREAD

**Issue by claudiugheorma** [pysathq/pysat#133] opened 2023-05-27 20:02 UTC
Hi there! Not really an issue, more so of a question since I am not sure what I may be doing wrong. I am trying to implement some cardinality constraints for a puzzle and when choosing pairwise encoding the solver works, but if i change the encoding to sequential counter (what I need to use) it does not work. I would keep working with pairwise encoding but I need to deal with k > 1 in some cases. I will post here how I add the cardinality constraints as the example. If I change the row and column counts to only include one 1 each, the seq encoding works. I am bit a confused. I also tried other encodings listed from the documentation and none of them seem to work for an example like this. Hope somebody can help me out! 
 
n = m = 5
row_counts = [1, 1, 1, 1, 1]
col_counts = [1, 1, 1, 1, 1]

variables = [[(i * m + j + 1) for j in range(m)] for i in range(n)]

# Add row constraints
for i in range(n):
    constraint = CardEnc.equals(lits=variables[i], bound=row_counts[i], encoding=1)
    solver.append_formula(constraint.clauses)
    

# Add column constraints
for j in range(m):
    constraint = CardEnc.equals(lits=[variables[i][j] for i in range(n)], bound=col_counts[j], encoding=1)
    solver.append_formula(constraint.clauses)

**Comment by claudiugheorma** [comment] 2023-05-27 20:06
Also to note, I tried other encodings listed from the documentation and none of them seem to work for an example like this.

**Comment by alexeyignatiev** [comment] 2023-05-27 23:04
It is because the non-pairwise encoders introduce auxiliary variables. In your case, the encoder is called multiple times, which it does not know about, and it hence reuses the same auxiliary variables in different constraints. As a result, the final formula loses its intended semantics.

You need to [count the auxiliary variables](https://pysathq.github.io/docs/html/api/card.html#pysat.card.CardEnc.atleast) introduced in each encoder calls and make sure the sets of auxiliary variables do not intersect. You can either pass a `top_id` or a `vpool` variable for that. The latter is simpler to use as it will apply counting for you. 

A modified example of yours would look like this, if you used a `vpool`:

```python

from pysat.formula import IDPool
from pysat.card import *

n = m = 5
row_counts = [1, 1, 1, 1, 1]
col_counts = [1, 1, 1, 1, 1]

variables = [[(i * m + j + 1) for j in range(m)] for i in range(n)]

# create a new pool object
pool = IDPool(start_from=max(variables) + 1)

# add row constraints
for i in range(n):
	constraint = CardEnc.equals(lits=variables[i], bound=row_counts[i], vpool=pool, encoding=EncType.seqcounter)
	solver.append_formula(constraint.clauses)

# add column constraints
for j in range(m):
constraint = CardEnc.equals(lits=[variables[i][j] for i in range(n)], bound=col_counts[j], vpool=pool, encoding=EncType.seqcounter)
solver.append_formula(constraint.clauses)
```

This (or something along these lines) should work as intended.

**Comment by claudiugheorma** [comment] 2023-05-27 23:17
Oh god! Thank you so much! Works perfectly now. I was thinking it might have to do with that but wasn't sure how to follow with that.

**Comment by alexeyignatiev** [comment] 2023-05-27 23:49
Sure, no worries, I am glad it helped! Closing the issue now.

**Closed by alexeyignatiev** 2023-05-27 23:49 UTC
