### ISSUE TITLE
solve returns false, but the formula is satisfiable

### ISSUE THREAD

**Issue by ningit** [pysathq/pysat#169] opened 2024-04-16 21:20 UTC
The following piece of code produces `False` and `T` as output, i.e. it says that the formula `f` is not satisfiable, then simplifies it to true with some assumptions. 

```python
from pysat.formula import Atom
from pysat.solvers import Solver

x = Atom(1)
y = Atom(2)  # true
z = Atom(3)  # false
t = Atom(4)  # true

f = ((~y >> x) & t) & ~((y >> z) & (~y >> t))

with Solver(bootstrap_with=f) as solver:
	print(solver.solve())  # False

print(f.simplified([y, ~z, t]))  # T
```

The formula is satisfiable, so either I am not properly using the library or this is a bug in `solve`.

**Comment by alexeyignatiev** [comment] 2024-04-16 21:29
Most likely it is an issue in classification.

**Comment by alexeyignatiev** [comment] 2024-04-16 21:32
@brossignol, by any chance does this work in your patched version?

**Comment by alexeyignatiev** [comment] 2024-04-16 23:04
@ningit, I've just checked and it is true that the issue was caused by classification of negation terms, and it seems fixed in the [PR](https://github.com/pysathq/pysat/pull/168) prepared by @brossignol.

**Comment by brossignol** [comment] 2024-04-17 00:09
The patch fix it.

It is the same problem. The double negation of Atom(2) adds [-2] to the clauses when it should not.

**Comment by alexeyignatiev** [comment] 2024-04-17 00:11
Thanks for confirming. Then I am closing it.

**Closed by alexeyignatiev** 2024-04-17 00:11 UTC

**Comment by ningit** [comment] 2024-04-17 08:18
It also works for me. Thank you!
